### PR TITLE
Fixed RS256 series PKCS#1 padding

### PR DESCRIPTION
**Pull request by kkazuo**
ironclad:sign-message and ironclad:verify-signature are both RSA raw primitive function,
thus you must do PKCS#1 padding yourself.

### CODE REVIEW

**Comment by fukamachi** [comment]
Thank you for your contribution!
I'm not an expert about security, so I'm not sure why the padding is important.

Is this blog entry what you intended? http://inaz2.hatenablog.com/entry/2016/01/26/222303

**Comment by kkazuo** [comment]
Thank you for your interest.

I am not intended for security reason, but for practical aspects in the real world use case of JWT verify.
If I have this patch, I can verify RS256 Open ID Connect id_token by myself with public key that was provided by OIDC issuer.
RS256 padding scheme is specified by RFC (probably), and verifing without padding will get always invalid answer.
Could you try to verify JWT RS256 key like Google accounts?
You can access OpenIDC endpoints, like this: curl https://accounts.google.com/.well-known/openid-configuration -s| jq
And you can get JWKs endpoints: curl https://www.googleapis.com/oauth2/v3/certs -s|jq
Yes, you got JWKs:

```
{
  "kty": "RSA",
  "alg": "RS256",
  "use": "sig",
  "kid": "3bcf0b3cc862a0ac77092f72b4dfdb20a8100df0",
  "n": "oV4G2mKC_EbVIOiqwP2yWY1zrXOkGoNz9T4tjzv1ht9h4fyMmQW8dTeVdlV1Qxal71NSQsBzIPfHl4U4Tz9ZiIh0DLQOHCVU6EjrBpZfYdHoWsR1mJT0fa4h63BOWVgWu76KFSESy5v15DMROXBDUo9-tThr9y9a1ssvCB1oPUv4heMJvJQsVM4Ua7ZVKXpzTEL17mY_qxTwSzfKPG6xwPWKnDMVJqgXyHQ9Z5FXPFx7g6JUZ5kT5EGl2-5BziIfXBpu8RGvaMPpldj486k9WgaUq8jJ7LQfN6YW0CrXS_lq6FKSV7SEw-vLCeiV3I-p5-8yKoLsbWoOd8UqH8sY1w",
  "e": "AQAB"
}
```

This is public key. You can create public key object with using ironclad.
Here is my sample code:

```
(defun key (n e)
  (let ((n (ironclad:octets-to-integer (jose/base64:base64url-decode n)))
        (e (ironclad:octets-to-integer (jose/base64:base64url-decode e))))
    (ironclad:make-public-key :rsa :n n :e e)))
```

Now. Let's verify.

```
(jose/decode :rs256 (key n e) id_token-except-signature-part)
```

I can not show you my example id_token, because my valid id_token contains some sensitive information that login with Google accounts.

https://openid-foundation-japan.github.io/draft-ietf-jose-json-web-signature-14.ja.html#RS256Example

Thanks

**Comment by kkazuo** [comment]
I have found a some test vector.
You can check this site. http://kjur.github.io/jsjws/mobile/tool_jwt.html

I add test case, and I have fixed the bug in my pull req.

**Comment by kkazuo** [comment]
I have added non standard RSA key size tests.

**Comment by fukamachi** [comment]
Merged. Thank you for your contribution!

**Pull request merged**
